# Generated by Django 4.0 on 2022-01-20 11:27

from django.db import migrations, models
import django.db.models.deletion
import phone_field.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=255)),
                ('client_description', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('contact_number', phone_field.models.PhoneField(blank=True, help_text='Contact phone number', max_length=31)),
                ('address', models.CharField(max_length=255)),
                ('client_priority', models.CharField(max_length=255)),
                ('client_location', models.CharField(max_length=1000)),
                ('geofence_details', models.CharField(max_length=1000)),
            ],
            options={
                'verbose_name_plural': 'clients',
            },
        ),
        migrations.CreateModel(
            name='Client_history',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('history_deliveries', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_history', to='myapp.client')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_creator', to='auth.user')),
            ],
            options={
                'verbose_name_plural': 'clients_history',
                'ordering': ('-history_deliveries',),
            },
        ),
        migrations.CreateModel(
            name='Client_deliveries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_deliveries', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_deliveries', to='myapp.client')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_creator1', to='auth.user')),
            ],
            options={
                'verbose_name_plural': 'client_deliveries',
                'ordering': ('-scheduled_deliveries',),
            },
        ),
    ]
