# Generated by Django 4.0 on 2022-01-20 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client_deliveries',
            name='scheduled_deliveries',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='client_history',
            name='history_deliveries',
            field=models.DateTimeField(),
        ),
    ]
