# Generated by Django 4.0 on 2022-01-20 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_client_deliveries_scheduled_deliveries_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client_history',
            name='history_deliveries',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='myapp.client_deliveries'),
        ),
    ]
