# Generated by Django 4.0 on 2022-01-21 05:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_warehouse_alter_client_client_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehouse_history',
            name='history_deliveries',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history1', to='myapp.warehouse_deliveries'),
        ),
    ]
