# Generated by Django 4.0 on 2022-01-25 03:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_warehouse_history_history_deliveries'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='client_location',
        ),
    ]
