# Generated by Django 4.0.1 on 2022-01-26 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_remove_client_client_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_Id', models.CharField(max_length=255)),
                ('vehicle_Brand', models.CharField(max_length=255)),
                ('vehicle_Number', models.CharField(max_length=255)),
                ('vehicle_Type', models.CharField(max_length=255)),
                ('scheduled_Date', models.DateField()),
                ('scheduled_Location', models.CharField(max_length=255)),
                ('designated_Driver', models.CharField(max_length=255)),
                ('warehouse', models.CharField(max_length=255)),
                ('capacity', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'vehicle',
            },
        ),
    ]
